local this = {}

this.cookedMultiMin = 2.0
this.cookedMultiMax = 3.5

this.TYPE = {
    protein = "Protein",
    vegetable = "Vegetable",
    mushroom = "Mushroom",
    seasoning = "Seasoning",
    herb = "Herb",
    food = "Food",
    misc = "Other"
}

this.stewBuffs = {
    [this.TYPE.protein] = { min = 10, max = 40, id = "ashfall_stew_hearty"}, -- fortify health
    [this.TYPE.vegetable] = { min = 10, max = 40, id = "ashfall_stew_nutritious"}, --fortify fatigue
    [this.TYPE.mushroom] = { min = 10, max = 40, id = "ashfall_stew_chunky"}, --fortify magicka
    [this.TYPE.seasoning] = { min = 5, max = 20, id = "ashfall_stew_tasty"}, --fortify agility
    [this.TYPE.herb] = { min = 5, max = 20, id = "ashfall_stew_aromatic"} -- fortify personality
}


this.nutrition = {
    [this.TYPE.protein] = 15,
    [this.TYPE.vegetable] = 12,
    [this.TYPE.mushroom] = 10,
    [this.TYPE.seasoning] = 2,
    [this.TYPE.herb] = 5,
    [this.TYPE.food] = 40,
    [this.TYPE.misc] = 2,
}

this.ingredTypes = {
    ["ingred_human_meat_01"] = this.TYPE.protein,
    ["ingred_adamantium_ore_01"] = this.TYPE.misc,
    ["ingred_alit_hide_01"] = this.TYPE.misc,
    ["ingred_bc_ampoule_pod"] = this.TYPE.misc,
    ["ingred_ash_salts_01"] = this.TYPE.seasoning,
    ["ingred_ash_yam_01"] = this.TYPE.vegetable,
    ["ingred_bear_pelt"] = this.TYPE.misc,
    ["ingred_bittergreen_petals_01"] = this.TYPE.herb,
    ["ingred_black_anther_01"] = this.TYPE.herb,
    ["ingred_black_lichen_01"] = this.TYPE.misc,
    ["ingred_bloat_01"] = this.TYPE.misc,
    ["ingred_blood_innocent_unique"] = this.TYPE.misc,
    ["ingred_bonemeal_01"] = this.TYPE.misc,
    ["ingred_bread_01"] = this.TYPE.food,
    ["ingred_bread_01_UNI2"] = this.TYPE.food,
    ["ingred_boar_leather"] = this.TYPE.misc,
    ["ingred_bc_bungler's_bane"] = this.TYPE.mushroom,
    ["ingred_chokeweed_01"] = this.TYPE.herb,
    ["ingred_bc_coda_flower"] = this.TYPE.herb,
    ["ingred_comberry_01"] = this.TYPE.herb,
    ["ingred_corkbulb_root_01"] = this.TYPE.vegetable,
    ["ingred_corprus_weepings_01"] = this.TYPE.misc,
    ["ingred_crab_meat_01"] = this.TYPE.protein,
    ["ingred_daedra_skin_01"] = this.TYPE.misc,
    ["ingred_cursed_daedras_heart_01"] = this.TYPE.misc,
    ["ingred_daedras_heart_01"] = this.TYPE.misc,
    ["ingred_Dae_cursed_diamond_01"] = this.TYPE.misc,
    ["ingred_diamond_01"] = this.TYPE.misc,
    ["ingred_dreugh_wax_01"] = this.TYPE.misc,
    ["ingred_durzog_meat_01"] = this.TYPE.protein,
    ["ingred_ectoplasm_01"] = this.TYPE.misc,
    ["ingred_Dae_cursed_emerald_01"] = this.TYPE.misc,
    ["ingred_emerald_01"] = this.TYPE.misc,
    ["ingred_fire_petal_01"] = this.TYPE.herb,
    ["ingred_fire_salts_01"] = this.TYPE.seasoning,
    ["ingred_eyeball_unique"] = this.TYPE.misc,
    ["ingred_frost_salts_01"] = this.TYPE.seasoning,
    ["ingred_ghoul_heart_01"] = this.TYPE.misc,
    ["ingred_guar_hide_girith"] = this.TYPE.misc,
    ["ingred_gold_kanet_01"] = this.TYPE.herb,
    ["Ingred_golden_sedge_01"] = this.TYPE.herb,
    ["ingred_eyeball"] = this.TYPE.misc,
    ["ingred_gravedust_01"] = this.TYPE.misc,
    ["ingred_gravetar_01"] = this.TYPE.misc,
    ["ingred_green_lichen_01"] = this.TYPE.misc,
    ["ingred_guar_hide_01"] = this.TYPE.misc,
    ["ingred_hackle-lo_leaf_01"] = this.TYPE.herb,
    ["ingred_innocent_heart"] = this.TYPE.misc,
    ["ingred_udyrfrykte_heart"] = this.TYPE.misc,
    ["ingred_wolf_heart"] = this.TYPE.protein,
    ["ingred_heartwood_01"] = this.TYPE.misc,
    ["ingred_heather_01"] = this.TYPE.herb,
    ["ingred_holly_01"] = this.TYPE.herb,
    ["ingred_horker_tusk_01"] = this.TYPE.misc,
    ["Ingred_horn_lily_bulb_01"] = this.TYPE.vegetable,
    ["ingred_hound_meat_01"] = this.TYPE.protein,
    ["ingred_bc_hypha_facia"] = this.TYPE.mushroom,
    ["ingred_kagouti_hide_01"] = this.TYPE.misc,
    ["ingred_kresh_fiber_01"] = this.TYPE.herb,
    ["ingred_kwama_cuttle_01"] = this.TYPE.protein,
    ["ingred_6th_corprusmeat_05"] = this.TYPE.protein,
    ["food_kwama_egg_02"] = this.TYPE.protein,
    ["ingred_6th_corprusmeat_01"] = this.TYPE.protein,
    ["Ingred_lloramor_spines_01"] = this.TYPE.herb,
    ["ingred_russula_01"] = this.TYPE.mushroom,
    ["ingred_marshmerrow_01"] = this.TYPE.vegetable,
    ["ingred_guar_hide_marsus"] = this.TYPE.misc,
    ["Ingred_meadow_rye_01"] = this.TYPE.herb,
    ["ingred_6th_corprusmeat_06"] = this.TYPE.protein,
    ["ingred_6th_corprusmeat_03"] = this.TYPE.protein,
    ["ingred_scrib_jelly_02"] = this.TYPE.protein,
    ["ingred_moon_sugar_01"] = this.TYPE.misc,
    ["ingred_muck_01"] = this.TYPE.misc,
    ["ingred_bread_01_UNI3"] = this.TYPE.food,
    ["ingred_netch_leather_01"] = this.TYPE.misc,
    ["Ingred_nirthfly_stalks_01"] = this.TYPE.herb,
    ["Ingred_noble_sedge_01"] = this.TYPE.herb,
    ["ingred_Dae_cursed_pearl_01"] = this.TYPE.misc,
    ["ingred_pearl_01"] = this.TYPE.misc,
    ["ingred_emerald_pinetear"] = this.TYPE.misc,
    ["poison_goop00"] = this.TYPE.misc,
    ["ingred_racer_plumes_01"] = this.TYPE.misc,
    ["ingred_rat_meat_01"] = this.TYPE.protein,
    ["ingred_Dae_cursed_raw_ebony_01"] = this.TYPE.misc,
    ["ingred_raw_ebony_01"] = this.TYPE.misc,
    ["ingred_raw_glass_01"] = this.TYPE.misc,
    ["ingred_raw_glass_tinos"] = this.TYPE.misc,
    ["ingred_raw_Stalhrim_01"] = this.TYPE.misc,
    ["ingred_red_lichen_01"] = this.TYPE.misc,
    ["ingred_resin_01"] = this.TYPE.misc,
    ["ingred_belladonna_01"] = this.TYPE.herb,
    ["ingred_gold_kanet_unique"] = this.TYPE.herb,
    ["ingred_roobrush_01"] = this.TYPE.herb,
    ["ingred_Dae_cursed_ruby_01"] = this.TYPE.misc,
    ["ingred_ruby_01"] = this.TYPE.misc,
    ["ingred_saltrice_01"] = this.TYPE.vegetable,
    ["ingred_scales_01"] = this.TYPE.misc,
    ["ingred_scamp_skin_01"] = this.TYPE.misc,
    ["ingred_scathecraw_01"] = this.TYPE.misc,
    ["ingred_scrap_metal_01"] = this.TYPE.misc,
    ["Ingred_scrib_cabbage_01"] = this.TYPE.protein,
    ["ingred_scrib_jelly_01"] = this.TYPE.protein,
    ["ingred_scrib_jerky_01"] = this.TYPE.food,
    ["ingred_scuttle_01"] = this.TYPE.food,
    ["ingred_shalk_resin_01"] = this.TYPE.misc,
    ["ingred_sload_soap_01"] = this.TYPE.misc,
    ["ingred_6th_corprusmeat_07"] = this.TYPE.protein,
    ["food_kwama_egg_01"] = this.TYPE.protein,
    ["ingred_6th_corprusmeat_02"] = this.TYPE.protein,
    ["ingred_snowbear_pelt_unique"] = this.TYPE.misc,
    ["ingred_snowwolf_pelt_unique"] = this.TYPE.misc,
    ["ingred_bc_spore_pod"] = this.TYPE.herb,
    ["ingred_stoneflower_petals_01"] = this.TYPE.herb,
    ["Ingred_sweetpulp_01"] = this.TYPE.herb,
    ["Ingred_timsa-come-by_01"] = this.TYPE.herb,
    ["ingred_trama_root_01"] = this.TYPE.vegetable,
    ["ingred_treated_bittergreen_uniq"] = this.TYPE.herb,
    ["ingred_belladonna_02"] = this.TYPE.herb,
    ["ingred_vampire_dust_01"] = this.TYPE.misc,
    ["ingred_coprinus_01"] = this.TYPE.mushroom,
    ["ingred_void_salts_01"] = this.TYPE.seasoning,
    ["ingred_wickwheat_01"] = this.TYPE.herb,
    ["ingred_willow_anther_01"] = this.TYPE.herb,
    ["ingred_wolf_pelt"] = this.TYPE.misc,
    ["ingred_wolfsbane_01"] = this.TYPE.misc,
    ["ingred_6th_corprusmeat_04"] = this.TYPE.protein,
    
}

return this