local this = {}

this.activatorConfig = require("mer.Ashfall.config.activatorConfig")
this.conditionConfig = require("mer.Ashfall.config.conditionConfig")
this.foodConfig = require("mer.Ashfall.config.foodConfig")
this.ratingsConfig = require("mer.Ashfall.config.ratingsConfig")

this.objectIds = {
    firewood = "a_firewood",
    branch = "ashfall_firewood",
    campfire = "ashfall_campfire_01",
    cookingPot = "ashfall_cooking_pot",
    grill = "ashfall_grill",
    kettle = "ashfall_kettle"
} 


this.capacities = {
    cup = 50,
    goblet = 50,
    mug = 60,
    flask = 70,
    tankard = 90,
    bottle = 110,
    jug = 140,
    pitcher = 150,
    cookingPot = 150,
    kettle = 120,
    MAX = 150
}

this.bottleList = {
    --cups
    misc_com_redware_cup = { capacity = this.capacities.cup },
    misc_com_wood_cup_01 = { capacity = this.capacities.cup },
    misc_com_wood_cup_02 = { capacity = this.capacities.cup },
    misc_lw_cup = { capacity = this.capacities.cup },
    misc_imp_silverware_cup = { capacity = this.capacities.cup },
    misc_imp_silverware_cup_01 = { capacity = this.capacities.cup },

    --goblets
    misc_com_metal_goblet_01 = { capacity = this.capacities.goblet },
    misc_com_metal_goblet_02 = { capacity = this.capacities.goblet },
    misc_de_goblet_01 = { capacity = this.capacities.goblet },
    misc_de_goblet_02 = { capacity = this.capacities.goblet },
    misc_de_goblet_03 = { capacity = this.capacities.goblet },
    misc_de_goblet_04 = { capacity = this.capacities.goblet },
    misc_de_goblet_05 = { capacity = this.capacities.goblet },
    misc_de_goblet_06 = { capacity = this.capacities.goblet },
    misc_de_goblet_07 = { capacity = this.capacities.goblet },
    misc_de_goblet_08 = { capacity = this.capacities.goblet },
    misc_de_goblet_09 = { capacity = this.capacities.goblet },
    misc_dwrv_goblet00 = { capacity = this.capacities.goblet },
    misc_dwrv_goblet10 = { capacity = this.capacities.goblet },
    misc_dwrv_goblet00_uni = { capacity = this.capacities.goblet },
    misc_dwrv_goblet10_uni = { capacity = this.capacities.goblet },
    misc_dwrv_goblet10_tgcp = { capacity = this.capacities.goblet },
    misc_de_goblet_01_redas = { capacity = this.capacities.goblet },

    --tankards
    misc_com_tankard_01 = { capacity = this.capacities.tankard },
    misc_de_tankard_01 = { capacity = this.capacities.tankard },


    --mugs
    misc_dwrv_mug00 = { capacity = this.capacities.mug },
    misc_dwrv_mug00_uni = { capacity = this.capacities.mug },

    --flasks
    misc_flask_01 = { capacity = this.capacities.flask },
    misc_flask_02 = { capacity = this.capacities.flask },
    misc_flask_03 = { capacity = this.capacities.flask },
    misc_flask_04 = { capacity = this.capacities.flask },
    misc_com_redware_flask = { capacity = this.capacities.flask },
    misc_lw_flask = { capacity = this.capacities.flask },

    --bottles
    misc_com_bottle_01 = { capacity = this.capacities.bottle },
    misc_com_bottle_02 = { capacity = this.capacities.bottle },
    misc_com_bottle_04 = { capacity = this.capacities.bottle },
    misc_com_bottle_05 = { capacity = this.capacities.bottle },
    misc_com_bottle_06 = { capacity = this.capacities.bottle },
    
    misc_com_bottle_08 = { capacity = this.capacities.bottle },
    misc_com_bottle_09 = { capacity = this.capacities.bottle },
    misc_com_bottle_10 = { capacity = this.capacities.bottle },
    misc_com_bottle_11 = { capacity = this.capacities.bottle },
    misc_com_bottle_13 = { capacity = this.capacities.bottle },
    misc_com_bottle_14 = { capacity = this.capacities.bottle },
    misc_com_bottle_14_float = { capacity = this.capacities.bottle },
    misc_com_bottle_15 = { capacity = this.capacities.bottle },

    --jugs
    misc_com_bottle_03 = { capacity = this.capacities.jug },
    misc_com_bottle_07 = { capacity = this.capacities.jug },
    misc_com_bottle_07_float = { capacity = this.capacities.jug },
    misc_com_bottle_12 = { capacity = this.capacities.jug },

    --pitchers
    misc_de_pitcher_01 = { capacity = this.capacities.pitcher },
    misc_com_redware_pitcher = { capacity = this.capacities.pitcher },
    misc_com_pitcher_metal_01 = { capacity = this.capacities.pitcher },
    misc_dwrv_pitcher00 = { capacity = this.capacities.pitcher },
    misc_dwrv_pitcher00_uni = { capacity = this.capacities.pitcher },
    misc_imp_silverware_pitcher = { capacity = this.capacities.pitcher },
    misc_imp_silverware_pitcher_uni = { capacity = this.capacities.pitcher },
}

this.interiorTempValues = {
    default = 0,
    sewer = -20,
    eggmine = -30,
    ruin = -35,
    dungeon = -40,
    cave = -45,
    tomb = -50,
    barrow = -65
}
this.interiorTempPatterns = {
    [" sewers"]     = this.interiorTempValues.sewer,
    [" eggmine"]     = this.interiorTempValues.eggmine,
    [" egg mine"]     = this.interiorTempValues.eggmine,
    [" grotto"]     = this.interiorTempValues.dungeon,
    [" dungeon"]    = this.interiorTempValues.dungeon,
    [" tomb"]         = this.interiorTempValues.tomb,
    [" crypt"]         = this.interiorTempValues.tomb,
    [" catacomb"]     = this.interiorTempValues.tomb,
    [" cave"]         = this.interiorTempValues.cave,
    [" barrow"]     = this.interiorTempValues.barrow,

    --caves
    ["abanabi"] = this.interiorTempValues.cave,
    ["abernanit"] = this.interiorTempValues.cave,
    ["abinabi"] = this.interiorTempValues.cave,
    ["adanumuran"] = this.interiorTempValues.cave,
    ["addamasartus"] = this.interiorTempValues.cave,
    ["aharnabi"] = this.interiorTempValues.cave,
    ["aharunartus"] = this.interiorTempValues.cave,
    ["ahinipalit"] = this.interiorTempValues.cave,
    ["ainab"] = this.interiorTempValues.cave,
    ["ainat"] = this.interiorTempValues.cave,
    ["ansi"] = this.interiorTempValues.cave,
    ["ashanammu"] = this.interiorTempValues.cave,
    ["ashinabi"] = this.interiorTempValues.cave,
    ["ashirbadon"] = this.interiorTempValues.cave,
    ["ashir-dan"] = this.interiorTempValues.cave,
    ["ashmelech"] = this.interiorTempValues.cave,
    ["assarnud"] = this.interiorTempValues.cave,
    ["assemanu"] = this.interiorTempValues.cave,
    ["assu"] = this.interiorTempValues.cave,
    ["assumanu"] = this.interiorTempValues.cave,
    ["bensamsi"] = this.interiorTempValues.cave,
    ["beshara"] = this.interiorTempValues.cave,
    ["cavern of the incarnate"] = this.interiorTempValues.cave,
    ["corprusarium"] = this.interiorTempValues.cave,
    ["dubdilla"] = this.interiorTempValues.cave,
    ["dun-ahhe"] = this.interiorTempValues.cave,
    ["habinbaes"] = this.interiorTempValues.cave,
    ["hassour"] = this.interiorTempValues.cave,
    ["hinnabi"] = this.interiorTempValues.cave,
    ["ibar-dad"] = this.interiorTempValues.cave,
    ["ilunibi"] = this.interiorTempValues.cave,
    ["kora-dur"] = this.interiorTempValues.cave,
    ["kudanat"] = this.interiorTempValues.cave,
    ["kumarahaz"] = this.interiorTempValues.cave,
    ["kunirai"] = this.interiorTempValues.cave,
    ["maba-ilu"] = this.interiorTempValues.cave,
    ["mallapi"] = this.interiorTempValues.cave,
    ["mamaea"] = this.interiorTempValues.cave,
    ["mannammu"] = this.interiorTempValues.cave,
    ["maran-adon"] = this.interiorTempValues.cave,
    ["masseranit"] = this.interiorTempValues.cave,
    ["mat"] = this.interiorTempValues.cave,
    ["milk"] = this.interiorTempValues.cave,
    ["minabi"] = this.interiorTempValues.cave,
    ["missamsi"] = this.interiorTempValues.cave,
    ["mount kand, cavern"] = this.interiorTempValues.cave,
    ["nallit"] = this.interiorTempValues.cave,
    ["nammu"] = this.interiorTempValues.cave,
    ["nissintu"] = this.interiorTempValues.cave,
    ["nund"] = this.interiorTempValues.cave,
    ["odaishah"] = this.interiorTempValues.cave,
    ["odibaal"] = this.interiorTempValues.cave,
    ["odirnamat"] = this.interiorTempValues.cave,
    ["palansour"] = this.interiorTempValues.cave,
    ["panat"] = this.interiorTempValues.cave,
    ["pinsun"] = this.interiorTempValues.cave,
    ["piran"] = this.interiorTempValues.cave,
    ["pulk"] = this.interiorTempValues.cave,
    ["punabi"] = this.interiorTempValues.cave,
    ["punammu"] = this.interiorTempValues.cave,
    ["punsabanit"] = this.interiorTempValues.cave,
    ["rissun"] = this.interiorTempValues.cave,
    ["salmantu"] = this.interiorTempValues.cave,
    ["sanabi"] = this.interiorTempValues.cave,
    ["sanit"] = this.interiorTempValues.cave,
    ["sargon"] = this.interiorTempValues.cave,
    ["saturan"] = this.interiorTempValues.cave,
    ["sennananit"] = this.interiorTempValues.cave,
    ["sha-adnius"] = this.interiorTempValues.cave,
    ["shal"] = this.interiorTempValues.cave,
    ["shallit"] = this.interiorTempValues.cave,
    ["sharapli"] = this.interiorTempValues.cave,
    ["shurinbaal"] = this.interiorTempValues.cave,
    ["shushan"] = this.interiorTempValues.cave,
    ["shushishi"] = this.interiorTempValues.cave,
    ["sinsibadon"] = this.interiorTempValues.cave,
    ["subdun"] = this.interiorTempValues.cave,
    ["sud"] = this.interiorTempValues.cave,
    ["surirulk"] = this.interiorTempValues.cave,
    ["tin-ahhe"] = this.interiorTempValues.cave,
    ["tukushapal"] = this.interiorTempValues.cave,
    ["ulummusa"] = this.interiorTempValues.cave,
    ["yakanalit"] = this.interiorTempValues.cave,
    ["yakin"] = this.interiorTempValues.cave,
    ["yasamsi"] = this.interiorTempValues.cave,
    ["yesamsi"] = this.interiorTempValues.cave,
    ["zainsipilu"] = this.interiorTempValues.cave,
    ["zaintirari"] = this.interiorTempValues.cave,
    ["zanabi"] = this.interiorTempValues.cave,
    ["zebabi"] = this.interiorTempValues.cave,
    ["zenarbael"] = this.interiorTempValues.cave,

    --ruins
    ["aleft"] = this.interiorTempValues.ruin,
    ["arkngthand"] = this.interiorTempValues.ruin,
    ["arkngthunch-sturdumz"] = this.interiorTempValues.ruin,
    ["bethamez"] = this.interiorTempValues.ruin,
    ["bthanchend"] = this.interiorTempValues.ruin,
    ["bthuand"] = this.interiorTempValues.ruin,
    ["bthungthumz"] = this.interiorTempValues.ruin,
    ["dagoth ur"] = this.interiorTempValues.ruin,
    ["druscashti"] = this.interiorTempValues.ruin,
    ["endusal"] = this.interiorTempValues.ruin,
    ["galom daeus"] = this.interiorTempValues.ruin,
    ["mudan"] = this.interiorTempValues.ruin,
    ["mzahnch"] = this.interiorTempValues.ruin,
    ["mzanchend"] = this.interiorTempValues.ruin,
    ["mzuleft"] = this.interiorTempValues.ruin,
    ["nchardahrk"] = this.interiorTempValues.ruin,
    ["nchardumz"] = this.interiorTempValues.ruin,
    ["nchuleft"] = this.interiorTempValues.ruin,
    ["nchuleftingth"] = this.interiorTempValues.ruin,
    ["nchurdamz"] = this.interiorTempValues.ruin,
    ["odrosal"] = this.interiorTempValues.ruin,
    ["tureynulal"] = this.interiorTempValues.ruin,
    ["vemynal"] = this.interiorTempValues.ruin,
}


return this