
return {
    enableTemperatureEffects = true,
    enableHunger = true,
    enableThirst = true,
    enableSleep = true,
    enableCooking = false,
    showTemp = true,
    showHunger = true,
    showThirst = true,
    showSleep = true,
    showWetness = false,
    showFrostBreath = true,
    illegalHarvest = true,
    hungerRate = 20,
    thirstRate = 30,
    loseSleepRate = 50,
    loseSleepWaiting = 30,
    gainSleepRate = 80,
    gainSleepBed = 120,
}